#!/bin/bash

mkdir -p /app/ssl
cd /app/ssl

if [[ ! -f dvswitch.crt || ! -f dvswitch.key ]]; then
    apk --no-cache add openssl
    openssl req -newkey rsa:2048 -nodes -keyout dvswitch.key \
    -x509 -out dvswitch.crt \
    -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com"
    apk --no-cache del openssl
fi

cd /app
/app/Analog_Reflector -f /data/Analog_Reflector.json
